### ISSUE TITLE
Env vars are not injected into the docker build

### ISSUE THREAD

**Issue by ge4r0** [alcharra/docker-deploy-action-go#11]
Thank you for this gh action - it works really fast!

I'm struggling to deploy `postgres` image as it complains about not having required env vars. 

My configuration looks like this:
```yml
        uses: alcharra/docker-deploy-action-go@v1.5.0
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_port: ${{ secrets.SSH_PORT }}

          project_path: /opt/deploy
          deploy_file: 'docker-compose.dev.yml'
          mode: stack
          stack_name: test-dev
          docker_prune: system
          enable_rollback: true
          env_vars: |
            PORT=3000
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
```

The .env file is properly generated and transferred to the VPS. The problem is that it doesn't seem to be used when the image is build. Any ideas what's wrong?

For testing I even tried to deploy the simplest container to check if this env exists:
```yml 
  print-password:
    image: alpine:latest
    command: ['sh', '-c', 'echo ${POSTGRES_PASSWORD}']
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - network-overlay
```
