### ISSUE TITLE
2.0.0 - validation issue

### ISSUE THREAD

**Issue by ge4r0** [alcharra/docker-deploy-action-go#17]
I've upgraded from 1.5.1 to 2.0.0 and the deployments started to fail:

<img width="495" alt="Image" src="https://github.com/user-attachments/assets/ad88c037-0fe0-4ff6-8bcc-5700b59a62a8" />

Lines point to normal env vars like:
```yml
    environment:
      - POSTGRES_HOST=postgres
```

Besides that, the new logging format is super nice. I really like it

**Comment by ge4r0** [comment]
the error is gone but it still wants me to get rid of `build` property from the docker compose which I understand is not used by docker stack but it can be useful to build docker compose locally. Do you think there's a chance to make validation less picky or it doesn't really make sense?

Thanks for the help! I appreciate your input

**Comment by alcharra** [comment]
✅ This is now supported as of [v2.0.1](https://github.com/alcharra/docker-deploy-action-go/releases/tag/v2.0.1).

You can now define ``environment`` and ``labels`` using either a map or a list of ``KEY=VALUE`` pairs.

**Example – both formats are valid:**

```yaml
services:
  app:
    image: myapp
    environment:
      - FOO=bar
      - BAZ=qux
    labels:
      - "com.example.description=example app"
      - "com.example.version=1.0"
```

```yaml
services:
  app:
    image: myapp
    environment:
      FOO: bar
      BAZ: qux
    labels:
      com.example.description: "example app"
      com.example.version: "1.0"
```

Both styles are parsed consistently during validation.

Let me know if anything else would be useful!
